### ISSUE TITLE
[Question] "Reverse" tunnel scenario

### ISSUE THREAD

**Issue by git-noise** [xnuter/http-tunnel#9]
Hello,

Many thanks for the project.
I am not a specialist on these topics and wondered if the present project could be adapted to a reverse-tunnel situation. By reverse tunnel I mean having a client initiating the connection to the server (let's say behind a residential NAT ISP) and having the possibility to tunnel back data from the server back to the client - as an example to reach to reach private subnets. I understand it is currently no possible, but would that be easily doable?

Many thanks,

Best

**Comment by xnuter** [comment]
If a server is behind a NAT, you can have a node with a TCP proxy outside of the NAT boundaries and connect to it from the server machine (using again a TCP proxy). Then your clients may connect to that TCP proxy. So essentially you can establish a bridge from the server to a machine outside of the NAT boundaries. Of course it is a bit clunky and then the question is why host a server behind NAT and not somewhere else?

This app supports the TCP proxy mode, btw. I hope this hepls.

**Comment by git-noise** [comment]
Hello and thanks for your answer.

Indeed that would be a possibility, but that is essentially two tunnels, one from behind NAT to Outside NAT server, and then back-in via a second tcp-proxy as you mentioned.

What I had in mind taking the following terminology:
- client: where http-tunnel is run
- proxy-server: to where http-tunnel is building the tunnel and proxying the traffic
was more to use only one tunnel to do that, so instead of having http-tunnel only encapsulate and forward traffic back and forth from the client to the proxy-server (so client-initiated and returning traffic), also be able to haul-back data from the proxy-server back to the client (which may be behind a NAT) - even if that traffic was not necessarily initiated from the client. A bit like what ngrok and the likes are doing I guess. The idea here would be to benefit from an already existing stream without re-encapsulating the traffic back in another tunnel layer.

That may of course, not at all be a use-case for this project, but as you seemed very proficient with streams in rust I figured you may have some insight if it was achievable with it, or if it would be something entirely different.

Many thanks for taking the time.

Best

**Comment by xnuter** [comment]
I see. This seems to be outside of the scope of this project. However, I can help you to review design/code if you decide to take on that task

**Comment by git-noise** [comment]
Many thanks, I'll keep you in the loop if I end up taking it on.
